<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('<a href="http://productify.com/" target="_blank"><strong>Productify.com</strong></a> Extension - This module makes it easy to import products from <a href="http://productify.com/" target="_blank"><strong>Productify.com</strong></a>.')?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">

    <div class="fieldset fieldset-wide" id="group_4fieldset_group_4">
        <h1>Processing!</h1>
        Import from <a href="http://productify.com" target="_blank">productify.com</a> is being processed at the background. <br/>
        It might take several minutes. Please be patient. <strong>You may close your browser.</strong>
        <br/>Once done, you'll be automatically receiving an email notification to the assigned mailing address.<br/><br/>
        <strong>Note: </strong>Please note as part of this import process new categories may have been created. Please check your categories and enable as necessary.<br/>
        Products may not be visible until this is completed.
        
<!--        <h1>Complete!</h1>-->
<!--        Congratulations, import from <a href="productify.com">productify.com</a> is complete!<br/>-->
<!---->
<!--        <strong>Note: </strong>Please note as part of this import process new categories may have been created. Please check your categories and enable as necessary.<br/>-->
<!--        Products may not be visible until this is completed.-->
    </div>
</div>